WebBHDTCHUNG/WebBHDTCHUNG/Areas/Admin/Controllers/WarrantiController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebBHDTCHUNG.Areas.Admin.Data;
using WebBHDTCHUNG.Models;

namespace WebBHDTCHUNG.Areas.Admin.Controllers
{
    [Authorize]
    public class WarrantiController : Controller
    {
        private CMSBHDTCHUNGEntities db = new CMSBHDTCHUNGEntities();
        string userId = "";
        public ActionResult Index(int? page, int? status)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (User.Identity.Name == "administrator")
            {
                var model1 = from a in db.ProductWarrantis
                             join b in db.Products on a.ProductId equals b.Id
                             into temp1
                             from t1 in temp1.DefaultIfEmpty()
                             join c in db.Customers on a.CustomerId equals c.Id
                             into temp2
                             from t2 in temp2.DefaultIfEmpty()
                             select new WarrantiViewModel()
                             {
                                 ProductName = t1.Name,
                                 Serial = t1.Serial,
                                 CustomerName = t2.Name,
                                 PhoneWarranti = a.PhoneWarranti,
                                 Category = a.Category,
                                 Status = a.Status,
                                 Note = a.Note,
                                 Createdate = a.Createdate,
                                 Createby = a.Createby,
                                 Checkdate = a.Checkdate,
                                 Checkby = a.Checkby,
                                 Id = a.Id,
                             };
                // return View(model1);
                if (status != null)
                {
                    model1 = model1.Where(c => c.Status == status);
                    ViewBag.Channel = status;
                }
                return View(model1.OrderByDescending(x => x.Id).ToPagedList(pageNumber, pageSize));
            }
            string partner = db.AspNetUsers.Find(User.Identity.GetUserId()).Createby;
            if (User.IsInRole("Mod"))
            {
                userId = partner;
            }
            else
            {
                userId = User.Identity.GetUserId();
            }
            var model = from a in db.ProductWarrantis
                        where a.Createby == userId
                        join b in db.Products on a.ProductId equals b.Id
                        into temp1
                        from t1 in temp1.DefaultIfEmpty()
                        join c in db.Customers on a.CustomerId equals c.Id
                        into temp2
                        from t2 in temp2.DefaultIfEmpty()
                        select new WarrantiViewModel()
                        {
                            ProductName = t1.Name,
                            Serial = t1.Serial,
                            CustomerName = t2.Name,
                            PhoneWarranti = a.PhoneWarranti,
                            Category = a.Category,
                            Status = a.Status,
                            Note = a.Note,
                            Createdate = a.Createdate,
                            Createby = a.Createby,
                            Checkdate = a.Checkdate,
                            Checkby = a.Checkby,
                            Id = a.Id,
                        };

            if (status != null)
            {
                model = model.Where(c => c.Status == status);
                ViewBag.Channel = status;
            }
            return View(model.OrderByDescending(x => x.Id).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Create()
        {
            string userId = User.Identity.GetUserId();
            ViewBag.ProductId = new SelectList(db.Products.Where(a => a.Createby == userId).ToList(), "Id", "Name", null);
            ViewBag.CustomerId = new SelectList(db.Customers.Where(a => a.Createby == userId).ToList(), "Id", "Name", null);
            ProductWarranti productWarranti = new ProductWarranti();
            return View(productWarranti);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "")] ProductWarranti productWarranti)
        {
            if (ModelState.IsValid)
            {
                productWarranti.Createby = User.Identity.GetUserId();
                productWarranti.Createdate = DateTime.Now;
                db.ProductWarrantis.Add(productWarranti);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // ViewBag.ProductId = new SelectList(db.Products.Where(a => a.Createby == userId).ToList(), "Id", "Name", null);
            // ViewBag.CustomerId = new SelectList(db.Customers.Where(a => a.Createby == userId).ToList(), "Id", "Name", null);
            // return View(productWarranti);
            return RedirectToAction("Index");

        }
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductWarranti w = db.ProductWarrantis.Find(id);
            WarrantiViewModel productWarranti = new WarrantiViewModel()
            {
                Id = w.Id,
                ProductId = w.ProductId,
                CustomerId = w.CustomerId,
                PhoneWarranti = w.PhoneWarranti,
                Category = w.Category,
                Status = w.Status,
                Note = w.Note,
                Createdate = w.Createdate,
                Createby = w.Createby,
                Checkdate = w.Checkdate,
                Checkby = w.Checkby
            };
            if (productWarranti == null)
            {
                return HttpNotFound();
            }
            return View(productWarranti);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "")] WarrantiViewModel productWarranti)
        {
            if (ModelState.IsValid)
            {
                ProductWarranti pw = db.ProductWarrantis.Find(productWarranti.Id);
                pw.Checkby = User.Identity.GetUserId();
                pw.Checkdate = DateTime.Now;
                pw.Status = productWarranti.Status;
                pw.Note = productWarranti.Note;
                pw.Category = productWarranti.Category;
                pw.PhoneWarranti = productWarranti.PhoneWarranti;
                var getid = db.Products.Where(a => a.Createby == productWarranti.Createby).Where(a => a.Serial == productWarranti.Serial).SingleOrDefault();
                if (getid != null)
                {
                    pw.ProductId = getid.Id;
                }
                db.Entry(pw).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productWarranti);
        }
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductWarranti productWarranti = db.ProductWarrantis.Find(id);
            if (productWarranti == null)
            {
                return HttpNotFound();
            }
            return View(productWarranti);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ProductWarranti productWarranti = db.ProductWarrantis.Find(id);
            db.ProductWarrantis.Remove(productWarranti);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

WebBHDTCHUNG/WebBHDTCHUNG/Controllers/WarrantiController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebBHDTCHUNG.Models;

namespace WebBHDTCHUNG.Controllers
{
    [RoutePrefix("bao-hanh")]
    public class WarrantiController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        private CMSBHDTCHUNGEntities db = new CMSBHDTCHUNGEntities();
        [Route]
        public ActionResult Index()
        {
            ViewBag.url = Request.Url.AbsoluteUri;
            TempData["province"] = getProvince();
            return View();
        }

        [HttpPost]
        public ActionResult Send(string serial, string name, string phone, string province, string district, string address, string note, string email)
        {
            phone = Utils.FormatString.formatUserId(phone, 0);
            logger.Info(string.Format("{0} {1} {2} {3} {4} {5} {6} {7}", serial, name, phone, province, district, address, note, email));
            var product = db.Products.Where(a => a.Serial == serial).SingleOrDefault();
            if (product == null)
            {
                logger.Info("Không tìm thấy thông tin sản phẩm");
                return Json(ResResult("Không tìm thấy thông tin sản phẩm", null), JsonRequestBehavior.AllowGet);//san pham khong ton tai
            }
            else
            {
                logger.Info("Tìm thấy thông tin sản phẩm");
                logger.Info(string.Format("[BH] {0} {1} {2} {3} {4} {5} {6} {7}", phone, name, province, district, address, email, note, product.Createby));
                logger.Info("Add thông tin vào bảng ProductWantarie");
                long cusId = addCustomer(phone, name, province, district, address, email, product.Createby);
                addWarranti(product, cusId, phone, note, product.Createby);
                //neu partner su dung brandname, gui brandname den khach hang
                //checkSendBrandname(product.Createby, phone);
                logger.Info("warranti ok");
                return Json(ResResult("Thông tin bảo hành đã được gửi. Tổng đài sẽ liên hệ đến số điện thoại bạn đã gửi", null), JsonRequestBehavior.AllowGet);//san pham khong ton tai
            }

        }

        private void checkSendBrandname(string partner, string phone)
        {
            var brand = db.TempBrandnames.Find(partner);
            if (brand != null)
            {
                string mess = string.Format(brand.TempWarranti);
                int send = Utils.SendMTBrandname.SentMTMessage(mess, phone, brand.ShowName, brand.ShowName, "0");
                Brandname brandName = new Brandname()
                {
                    Status = send,
                    Message = mess,
                    Createdate = DateTime.Now,
                    PhoneSend = phone
                };
                db.Brandnames.Add(brandName);
                db.SaveChanges();
            }
        }

        private void addWarranti(Product product, long customer, string phone, string note, string partner)
        {
            var prodWarranti = new ProductWarranti()
            {
                ProductId = product.Id,
                CustomerId = customer,
                PhoneWarranti = phone,
                Note = note,
                Createdate = DateTime.Now,
                Createby = partner,
                Status = 0,
            };
            db.ProductWarrantis.Add(prodWarranti);
            db.SaveChanges();
        }
        private long addCustomer(string phone, string name, string province, string district, string address, string email, string create)
        {
            var customer = db.Customers.Where(a => a.Phone == phone && a.Createby == create).SingleOrDefault();
            if (customer != null)
            {
                if (customer.Name.Length == 0)
                {
                    customer.Name = name;
                    customer.City = province;
                    customer.District = district;
                    customer.Address = address;
                    customer.Email = email;
                    db.Entry(customer).State = EntityState.Modified;
                    return db.SaveChanges();
                }
                else
                {
                    return customer.Id;
                }
            }
            else
            {
                var newcus = new Customer()
                {
                    Phone = phone,
                    Name = name,
                    City = province,
                    District = district,
                    Address = address,
                    Email = email,
                    Createdate = DateTime.Now,
                    Createby = create
                };
                db.Customers.Add(newcus);
                db.SaveChanges();
                return newcus.Id;
            }
        }

        public List<Province> getProvince()
        {
            var province = db.Provinces.OrderBy(a => a.Name).ToList();
            return province;
        }

        [HttpPost]
        public ActionResult GetCity(string name)
        {
            District city = new District();
            var id = db.Provinces.Where(s => s.Name == name).SingleOrDefault();//get id theo ten
            var provi = db.Districts.Where(x => x.ProvinceId == id.Id).ToList();//get ds quan huyen
            var ress = new List<String>();//add data vao response
            foreach (var i in provi)
            {
                ress.Add(i.Name);
            }
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(ress);//convert to json
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public string ResResult(string message, ProductActiveModel model)
        {
            Ress ress = new Ress()
            {
                message = message,
                prodActive = model
            };
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(ress);//convert to json
            return result;
        }
        public class Ress
        {
            public string message { get; set; }
            public ProductActiveModel prodActive { get; set; }
        }

    }
}

WebBHDTCHUNG/WebBHDTCHUNG/Areas/Admin/Views/Warranti/Create.cshtml
@model WebBHDTCHUNG.Models.ProductWarranti
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tạo mới bảo hành</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ProductId,  null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CustomerId,
       null,
              new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneWarranti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneWarranti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneWarranti, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.Createdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Createdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Createdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.Createby, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Createby, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Createby, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.Checkdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Checkdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Checkdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.Checkby, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Checkby, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Checkby, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebBHDTCHUNG/WebBHDTCHUNG/Areas/Admin/Views/Warranti/Delete.cshtml
@model WebBHDTCHUNG.Models.ProductWarranti

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductWarranti</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneWarranti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneWarranti)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Createdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Createdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Createby)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Createby)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Checkdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Checkdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Checkby)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Checkby)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebBHDTCHUNG/WebBHDTCHUNG/Areas/Admin/Views/Warranti/Index.cshtml
@model PagedList.IPagedList<WebBHDTCHUNG.Areas.Admin.Data.WarrantiViewModel>

@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}
@section scripts{
    <script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>
    <script>
        $(document).ready(function () {
            $("#btnExport").click(function () {
                let table = document.getElementsByTagName("table");
                TableToExcel.convert(table[0], { // html code may contain multiple tables so here we are refering to 1st table tag
                    name: `warranti.xlsx`, // fileName you could use any name
                    sheet: {
                        name: 'Sheet 1' // sheetName
                    }
                });
            });
        });
    </script>
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Bảo hành</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                @using (Html.BeginForm("Index", "Warranti", FormMethod.Get))
                {
                    <div class="col-md-6" style="padding-bottom:5px;">
                        <label>Lọc theo trạng thái</label>
                        @Html.DropDownList("status", new List<SelectListItem>{
                         new SelectListItem { Value = "" , Text = "--Chọn--" },
                         new SelectListItem { Value = "1" , Text = "Đã duyệt" },
                         new SelectListItem { Value = "0" , Text = "Mới" },
                      })

                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i> Lọc dữ liệu</button>
                    </div>
                }
                <div class="btn-right">
                    <a href="/admin/warranti/create" type="button" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i> Tạo mới</a>
                    <a id="btnExport" class="btn btn-success"><i class="fa fa-download" aria-hidden="true"></i> Export File</a>
                </div>
            </div>

            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" >
                        <thead>
                            <tr>
                                <th>Tên sản phẩm</th>
                                <th>Mã cào</th>
                                <th>Tên khách hàng</th>
                                <th>Sdt bảo hành</th>
                                <th>Trạng thái</th>
                                <th>Ngày báo</th>
                                <th>Mô tả</th>
                                <th>Ngày hoàn thành BH</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ProductName</td>
                                    <td>@item.Serial</td>
                                    <td>@item.CustomerName</td>
                                    <td>@item.PhoneWarranti</td>
                                    <td>
                                        @if (item.Status == 1)
                                        {
                                            <p class="btn-success text-center">Đã duyệt</p>
                                        }
                                        else
                                        {
                                            <p class="btn-danger text-center">Mới</p>
                                        }
                                    </td>
                                    <td>
                                        @if (item.Createdate != null)
                                        {
                                            @Convert.ToDateTime(item.Createdate).ToString("dd/MM/yyyy")
                                        }
                                    </td>
                                    <td>@item.Note</td>
                                    <td>
                                        @if (item.Checkdate != null)
                                        {
                                            @Convert.ToDateTime(item.Checkdate).ToString("dd/MM/yyyy")
                                        }
                                    </td>
                                    <td>
                                        @if (User.IsInRole("Partner") && item.Status != 1)
                                        {
                                            <a class="btn" href="/admin/warranti/edit/@item.Id"><i class="fa fa-edit fa-fw"></i></a>
                                            <a class="btn" href="/admin/warranti/delete/@item.Id"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Index",
         new { page, currentFilter = ViewBag.CurrentFilter, status = ViewBag.Channel }))
                    <p class="pageof">page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>